# .eslintrc.yml
# Copyright (C) 2020 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
extends: eslint:recommended
parserOptions:
  sourceType: module
  ecmaVersion: 2020 # This is required for 'import.meta'
env:
  es2017: true
  browser: true
root: true
